export const uiPackageName = '@financeapp/ui' as const;

export {
  componentMetrics,
  darkChartTokens,
  darkColors,
  darkElevation,
  darkTheme,
  fontFamilies,
  formatAmountInput,
  formatEditableMoneyInput,
  formatMoney,
  getCurrencyFractionDigits,
  getTheme,
  icon,
  interaction,
  lightChartTokens,
  lightColors,
  lightElevation,
  lightTheme,
  motion,
  parseMoneyInput,
  radius,
  spacing,
  stroke,
  themes,
  typography,
} from './tokens';
export type {
  ChartColors,
  ChartTokens,
  ColorScheme,
  DisabledColors,
  ElevationLevel,
  ElevationStyle,
  PastelColors,
  SpacingName,
  ThemeColors,
  ThemeTokens,
  TypographyName,
  TypographyTokens,
} from './tokens';

export {
  Button,
  Card,
  ChartFrame,
  Dialog,
  EmptyState,
  ErrorState,
  Input,
  ListRow,
  MoneyInput,
  OfflineBanner,
  PermissionState,
  Select,
  SensitiveValue,
  Sheet,
  Skeleton,
  ThemeProvider,
  Toast,
  useReducedMotion,
  useTheme,
} from './components';
export type {
  ButtonProps,
  ButtonVariant,
  CardProps,
  CardVariant,
  ChartFrameProps,
  DialogProps,
  EmptyStateProps,
  ErrorStateProps,
  InputProps,
  ListRowProps,
  MoneyInputProps,
  OfflineBannerProps,
  PermissionStateProps,
  PermissionStatus,
  SelectOption,
  SelectProps,
  SensitiveValueProps,
  SheetProps,
  SkeletonProps,
  ThemeContextValue,
  ThemeProviderProps,
  ToastProps,
  ToastVariant,
} from './components';

export { ResourceState } from './patterns';
export type { ResourceStateProps, ResourceStatus } from './patterns';
