export const FEATURE_IDS = [
  'F01',
  'F02',
  'F03',
  'F04',
  'F05',
  'F06',
  'F07',
  'F08',
  'F09',
  'F10',
  'F11',
  'F12',
  'F13',
  'F14',
  'F15',
  'F16',
  'F17',
  'F18',
  'F19',
  'F20',
  'F21',
  'F22',
  'F23',
  'F24',
] as const;

export type FeatureId = (typeof FEATURE_IDS)[number];
export type RoutePath = '/' | `/${string}`;

export const READINESS_STATUSES = ['WIREFRAME READY', 'BACKEND READY', 'INTEGRATED'] as const;

export type ReadinessStatus = (typeof READINESS_STATUSES)[number];
export type BottomTabId = 'home' | 'transactions' | 'planning' | 'reports' | 'profile';
export type NavigationGroup = 'public' | BottomTabId;

export interface RouteManifestEntry {
  featureId: FeatureId;
  routeId: string;
  path: RoutePath;
  navigationGroup: NavigationGroup;
  tab: BottomTabId | null;
  title: string;
  readiness: ReadinessStatus;
}

export const ROUTE_MANIFEST = [
  {
    featureId: 'F01',
    routeId: 'onboarding',
    path: '/onboarding',
    navigationGroup: 'public',
    tab: null,
    title: 'Onboarding & autentikasi',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F02',
    routeId: 'financial-preferences',
    path: '/profile/preferences',
    navigationGroup: 'profile',
    tab: 'profile',
    title: 'Profil keuangan & preferensi',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F03',
    routeId: 'accounts',
    path: '/accounts',
    navigationGroup: 'home',
    tab: 'home',
    title: 'Akun, dompet, aset & liabilitas',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F04',
    routeId: 'categories',
    path: '/categories',
    navigationGroup: 'transactions',
    tab: 'transactions',
    title: 'Kategori, tag & aturan klasifikasi',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F05',
    routeId: 'transactions',
    path: '/transactions',
    navigationGroup: 'transactions',
    tab: 'transactions',
    title: 'Transaksi manual',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F06',
    routeId: 'transfers',
    path: '/transfers',
    navigationGroup: 'transactions',
    tab: 'transactions',
    title: 'Transfer, split & adjustment',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F07',
    routeId: 'receipt-capture',
    path: '/receipt-capture',
    navigationGroup: 'transactions',
    tab: 'transactions',
    title: 'Scan struk & OCR',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F08',
    routeId: 'voice-capture',
    path: '/voice-capture',
    navigationGroup: 'transactions',
    tab: 'transactions',
    title: 'Input suara',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F09',
    routeId: 'home',
    path: '/',
    navigationGroup: 'home',
    tab: 'home',
    title: 'Dashboard & ringkasan harian',
    readiness: 'INTEGRATED',
  },
  {
    featureId: 'F10',
    routeId: 'reports',
    path: '/reports',
    navigationGroup: 'reports',
    tab: 'reports',
    title: 'Laporan arus kas & net worth',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F11',
    routeId: 'budgets',
    path: '/planning/budgets',
    navigationGroup: 'planning',
    tab: 'planning',
    title: 'Anggaran',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F12',
    routeId: 'goals',
    path: '/planning/goals',
    navigationGroup: 'planning',
    tab: 'planning',
    title: 'Tujuan & sinking funds',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F13',
    routeId: 'recurring',
    path: '/planning/recurring',
    navigationGroup: 'planning',
    tab: 'planning',
    title: 'Transaksi berulang, tagihan & langganan',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F14',
    routeId: 'debts',
    path: '/planning/debts',
    navigationGroup: 'planning',
    tab: 'planning',
    title: 'Utang, piutang & pinjaman tercatat',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F15',
    routeId: 'forecast',
    path: '/planning/forecast',
    navigationGroup: 'planning',
    tab: 'planning',
    title: 'Kalender & forecast',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F16',
    routeId: 'review',
    path: '/transactions/review',
    navigationGroup: 'transactions',
    tab: 'transactions',
    title: 'Pencarian, review & rekonsiliasi',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F17',
    routeId: 'currency',
    path: '/planning/currency',
    navigationGroup: 'planning',
    tab: 'planning',
    title: 'Multi-currency',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F18',
    routeId: 'sync-status',
    path: '/sync',
    navigationGroup: 'home',
    tab: 'home',
    title: 'Offline-first & sinkronisasi',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F19',
    routeId: 'notifications',
    path: '/notifications',
    navigationGroup: 'profile',
    tab: 'profile',
    title: 'Notifikasi, widget & shortcut',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F20',
    routeId: 'import-export',
    path: '/profile/import-export',
    navigationGroup: 'profile',
    tab: 'profile',
    title: 'Impor, ekspor & backup pengguna',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F21',
    routeId: 'insights',
    path: '/reports/insights',
    navigationGroup: 'reports',
    tab: 'reports',
    title: 'AI insights & assistant',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F22',
    routeId: 'connections',
    path: '/profile/connections',
    navigationGroup: 'profile',
    tab: 'profile',
    title: 'Sinkronisasi bank/e-wallet',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F23',
    routeId: 'household',
    path: '/profile/household',
    navigationGroup: 'profile',
    tab: 'profile',
    title: 'Household sharing',
    readiness: 'WIREFRAME READY',
  },
  {
    featureId: 'F24',
    routeId: 'security',
    path: '/profile/security',
    navigationGroup: 'profile',
    tab: 'profile',
    title: 'Keamanan, privasi & kontrol akun',
    readiness: 'WIREFRAME READY',
  },
] as const satisfies readonly RouteManifestEntry[];

export const BOTTOM_TABS = [
  {
    id: 'home',
    label: 'Home',
    path: '/',
    screenName: 'index',
    icon: '⌂',
    isPrimaryTab: true,
  },
  {
    id: 'transactions',
    label: 'Transactions',
    path: '/transactions',
    screenName: 'transactions',
    icon: '↕',
    isPrimaryTab: true,
  },
  {
    id: 'planning',
    label: 'Planning',
    path: '/planning',
    screenName: 'planning',
    icon: '◫',
    isPrimaryTab: true,
  },
  {
    id: 'reports',
    label: 'Reports',
    path: '/reports',
    screenName: 'reports',
    icon: '▥',
    isPrimaryTab: true,
  },
  {
    id: 'profile',
    label: 'Profile',
    path: '/profile',
    screenName: 'profile',
    icon: '♙',
    isPrimaryTab: true,
  },
] as const;

export type BottomTabDefinition = (typeof BOTTOM_TABS)[number];
